apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rocketguard-rz2-redirect
spec:
  hosts:
    - rocketguard.default.svc.cluster.local
  http:
    - route:
        - destination:
            host: rocketguard.default.svc.cluster.local
            subset: rz1
          weight: 100