apiVersion: v1
kind: Service
metadata:
  name: rocketguard
  labels:
    app.kubernetes.io/name: rocketguard
spec:
  selector:
    app.kubernetes.io/name: rocketguard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080