apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: rocketguard
spec:
  hosts:
    - rocketguard.default.svc.cluster.local
  http:
    - route:
        - destination:
            host: rocketguard.default.svc.cluster.local
          weight: 100